version: "3.9"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_DB: "gkeeper"
      POSTGRES_USER: "gkeeper"
      POSTGRES_PASSWORD: "example"       
    ports:
      - "5432:5432"
 
