openapi: 3.0.0
info:
  title: "GophKeeper API"
  description: "API for GophKeeper, a secure password manager"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Local development server"

paths:
  /register:
    post:
      summary: "Register a new user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "User successfully registered"
        '400':
          description: "Invalid request payload"

  /login:
    post:
      summary: "Login and get authentication token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "Successfully logged in, returns authentication token"
        '401':
          description: "Invalid credentials"

  /data:
    get:
      summary: "Get user's private data"
      parameters:
        - name: "Authorization"
          in: "header"
          description: "Bearer token obtained during login"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Successfully retrieved user's private data"
        '401':
          description: "Unauthorized, invalid or expired token"

  /data/{id}:
    get:
      summary: "Get a specific private data entry by ID"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the private data entry"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Successfully retrieved private data entry"
        '401':
          description: "Unauthorized, invalid or expired token"
        '404':
          description: "Private data entry not found"

    put:
      summary: "Update a specific private data entry by ID"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the private data entry"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "Successfully updated private data entry"
        '401':
          description: "Unauthorized, invalid or expired token"
        '404':
          description: "Private data entry not found"

    delete:
      summary: "Delete a specific private data entry by ID"
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the private data entry"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Successfully deleted private data entry"
        '401':
          description: "Unauthorized, invalid or expired token"
        '404':
          description: "Private data entry not found"

  /sync:
    post:
      summary: "Synchronize data between authorized clients"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      password:
                        type: string
      responses:
        '200':
          description: "Successfully synchronized data"
        '401':
          description: "Unauthorized, invalid or expired token"

