// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT _EDIT.
package controllers

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strconv"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	"go.uber.org/zap/zapcore"
)

// PostAddDataTableUserIDEntryIDJSONBody defines parameters for PostAddDataTableUserIDEntryID.
type PostAddDataTableUserIDEntryIDJSONBody map[string]string

// PostLoginJSONBody defines parameters for PostLogin.
type PostLoginJSONBody struct {
	Password string `json:"password,omitempty"`
	Username string `json:"username,omitempty"`
}

// PostRegisterJSONBody defines parameters for PostRegister.
type PostRegisterJSONBody struct {
	Password string `json:"password,omitempty"`
	Username string `json:"username,omitempty"`
}

// PutUpdateDataTableUserIDEntryIDJSONBody defines parameters for PutUpdateDataTableUserIDEntryID.
type PutUpdateDataTableUserIDEntryIDJSONBody map[string]string

// PostAddDataTableUserIDEntryIDJSONRequestBody defines body for PostAddDataTableUserIDEntryID for application/json ContentType.
type PostAddDataTableUserIDEntryIDJSONRequestBody PostAddDataTableUserIDEntryIDJSONBody

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody PostLoginJSONBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody PostRegisterJSONBody

// PutUpdateDataTableUserIDEntryIDJSONRequestBody defines body for PutUpdateDataTableUserIDEntryID for application/json ContentType.
type PutUpdateDataTableUserIDEntryIDJSONRequestBody PutUpdateDataTableUserIDEntryIDJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /addData/{table}/{userID}/{entryID})
	PostAddDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string)

	// (DELETE /deleteData/{table}/{userID}/{entryID})
	DeleteDeleteDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string)

	// (GET /getAllData/{table}/{userID})
	GetGetAllDataTableUserID(w http.ResponseWriter, r *http.Request, table string, userID int)

	// (GET /getData/{table}/{userID}/{entryID})
	GetGetDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string)

	// (GET /getFile/{userID}/{entryID})
	GetGetFileUserIDEntryID(w http.ResponseWriter, r *http.Request, userID int, entryID string)

	// (GET /getPassword/{username})
	GetGetPasswordUsername(w http.ResponseWriter, r *http.Request, username string)

	// (GET /getUserID/{username})
	GetGetUserIDUsername(w http.ResponseWriter, r *http.Request, username string)

	// (POST /login)
	PostLogin(w http.ResponseWriter, r *http.Request)

	// (POST /register)
	PostRegister(w http.ResponseWriter, r *http.Request)

	// (POST /sendFile/{userID})
	PostSendFileUserID(w http.ResponseWriter, r *http.Request, userID int, fileName string)

	// (PUT /updateData/{table}/{userID}/{entryID})
	PutUpdateDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

type Storage interface {
	UserExists(ctx context.Context, username string) (bool, error)
	AddUser(ctx context.Context, username string, hashedPassword string) error
	GetPassword(ctx context.Context, username string) (string, error)
	GetUserID(ctx context.Context, username string) (int, error)
	AddData(ctx context.Context, table string, user_id int, entry_id string, data map[string]string) error
	UpdateData(ctx context.Context, table string, user_id int, entry_id string, data map[string]string) error
	DeleteData(ctx context.Context, table string, user_id int, entry_id string) error
	GetAllData(ctx context.Context, table string, user_id int) ([]map[string]string, error)
}

// Options represents an interface for parsing command line options.
type Options interface {
	// ParseFlags parses command line flags.
	ParseFlags()

	// RunAddr returns the address to run the application.
	RunAddr() string

	FileStoragePath() string
}

// Log represents an interface for logging functionality.
type Log interface {
	// Info logs an informational message with optional fields.
	Info(string, ...zapcore.Field)
}

// Authz represents an interface for user authorization functionality.
type Authz interface {
	// CreateJWTTokenForUser creates a JWT token for a specified user ID.
	CreateJWTTokenForUser(userID string) string
	IsBcryptHash(s string) bool
	CompareHashAndPassword(hashedPassword, password string) bool
}

// BaseController represents a basic controller for handling user requests.
// It includes handler methods for various operations.
type BaseController struct {
	storage Storage
	options Options
	log     Log
	authz   Authz
}

// Example usage:
//
//	controller := NewBaseController(memoryStorage, option, nLogger, worker, authz)
//	r.Mount("/", controller.Route())
//	flagRunAddr := option.RunAddr()
//	http.ListenAndServe(flagRunAddr, r)
func NewBaseController(storage Storage, options Options, log Log, authz Authz) *BaseController {
	instance := &BaseController{
		storage: storage,
		options: options,
		log:     log,
		authz:   authz,
	}

	return instance
}

// (POST /addData/{table}/{userID}/{entryID})
func (h *BaseController) PostAddDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string) {

	// Parse and decode the request body into a new 'map[string]string' value
	var requestBody map[string]string
	err := json.NewDecoder(r.Body).Decode(&requestBody)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call the 'AddData' method with the userID, table, and data from the request body
	err = h.storage.AddData(r.Context(), table, userID, entryID, requestBody)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// If everything goes well, respond with a status of '200 OK'
	w.WriteHeader(http.StatusOK)
}

// (DELETE /deleteData/{table}/{userID}/{entryID})
func (h *BaseController) DeleteDeleteDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

func (h *BaseController) GetGetAllDataTableUserID(w http.ResponseWriter, r *http.Request, table string, userID int) {
	// Получение данных из БД
	data, err := h.storage.GetAllData(r.Context(), table, userID)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Преобразование данных в JSON
	jsonData, err := json.Marshal(data)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Отправка данных
	w.Header().Set("Content-Type", "application/json")
	w.Write(jsonData)
}

// (GET /getData/{table}/{userID}/{entryID})
func (h *BaseController) GetGetDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /getFile/{userID}/{entryID})
func (h *BaseController) GetGetFileUserIDEntryID(w http.ResponseWriter, r *http.Request, userID int, entryID string) {

	// Путь к файлу
	filePath := filepath.Join(h.options.FileStoragePath(), entryID)
	// Проверка существования файла
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		http.Error(w, "Файл не найден", http.StatusNotFound)
		return
	}

	// Отправка файла
	http.ServeFile(w, r, filePath)
}

// (GET /getPassword/{username})
func (h *BaseController) GetGetPasswordUsername(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /getUserID/{username})
func (h *BaseController) GetGetUserIDUsername(w http.ResponseWriter, r *http.Request, username string) {
	// Получаем UserID из базы данных
	userID, err := h.storage.GetUserID(r.Context(), username)
	if err != nil {
		// Если произошла ошибка, отправляем статус 500 и сообщение об ошибке
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Преобразуем UserID в JSON
	userIDJSON, err := json.Marshal(userID)
	if err != nil {
		// Если произошла ошибка, отправляем статус 500 и сообщение об ошибке
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Устанавливаем заголовок Content-Type и отправляем UserID в ответе
	w.Header().Set("Content-Type", "application/json")
	w.Write(userIDJSON)
}

// (POST /login)
func (h *BaseController) PostLogin(w http.ResponseWriter, r *http.Request) {
	// Parse and decode the request body into a new 'PostLoginJSONRequestBody' value
	var requestBody PostLoginJSONRequestBody
	err := json.NewDecoder(r.Body).Decode(&requestBody)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	ctx := r.Context()

	// Попытка получить хешированный пароль пользователя из локальной базы данных
	hashedPassword, err := h.storage.GetPassword(ctx, requestBody.Username)
	if err != nil {
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}

	if h.authz.IsBcryptHash(requestBody.Password) {
		if hashedPassword != requestBody.Password {
			err := fmt.Errorf("Unauthorized")
			http.Error(w, err.Error(), http.StatusUnauthorized)
			return
		}
	} else {
		// Сравнение хешированного пароля с хешем введенного пароля
		if !h.authz.CompareHashAndPassword(hashedPassword, requestBody.Password) {
			err := fmt.Errorf("Unauthorized")
			http.Error(w, err.Error(), http.StatusUnauthorized)
			return
		}
	}

	userID, err := h.storage.GetUserID(ctx, requestBody.Username)
	if err != nil {
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}

	// Create a new JWT for the authenticated user
	token := h.authz.CreateJWTTokenForUser(strconv.Itoa(userID))

	// Prepare the response
	response := map[string]interface{}{
		"userID": userID,
		"token":  token,
	}

	// Convert the response to JSON
	responseBytes, err := json.Marshal(response)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Send the JWT and userID to the client in the response
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(responseBytes)
}

// (POST /register)
func (h *BaseController) PostRegister(w http.ResponseWriter, r *http.Request) {
	// Parse and decode the request body into a new 'PostRegisterJSONBody' value
	var requestBody PostRegisterJSONBody
	err := json.NewDecoder(r.Body).Decode(&requestBody)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Call the 'AddUser' method with the username and password from the request body
	err = h.storage.AddUser(r.Context(), requestBody.Username, requestBody.Password)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// If everything goes well, respond with a status of '200 OK'
	w.WriteHeader(http.StatusOK)
}

// (POST /sendFile/{userID})
// (POST /sendFile/{userID})
func (h *BaseController) PostSendFileUserID(w http.ResponseWriter, r *http.Request, userID int, fileName string) {
	// Чтение файла из тела запроса
	file, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "Ошибка при чтении файла", http.StatusInternalServerError)
		return
	}
	defer r.Body.Close()

	// Сохранение файла на сервере
	path := filepath.Join(h.options.FileStoragePath(), fileName)
	err = os.WriteFile(path, file, 0644)
	if err != nil {
		http.Error(w, "Ошибка при сохранении файла", http.StatusInternalServerError)
		return
	}

	// Отправка ответа
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "Файл успешно сохранен")
}

// (PUT /updateData/{table}/{userID}/{entryID})
func (h *BaseController) PutUpdateDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request, table string, userID int, entryID string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAddDataTableUserIDEntryID operation middleware
func (siw *ServerInterfaceWrapper) PostAddDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", chi.URLParam(r, "table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "entryID" -------------
	var entryID string

	err = runtime.BindStyledParameterWithOptions("simple", "entryID", chi.URLParam(r, "entryID"), &entryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAddDataTableUserIDEntryID(w, r, table, userID, entryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteDeleteDataTableUserIDEntryID operation middleware
func (siw *ServerInterfaceWrapper) DeleteDeleteDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", chi.URLParam(r, "table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "entryID" -------------
	var entryID string

	err = runtime.BindStyledParameterWithOptions("simple", "entryID", chi.URLParam(r, "entryID"), &entryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDeleteDataTableUserIDEntryID(w, r, table, userID, entryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGetAllDataTableUserID operation middleware
func (siw *ServerInterfaceWrapper) GetGetAllDataTableUserID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", chi.URLParam(r, "table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGetAllDataTableUserID(w, r, table, userID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGetDataTableUserIDEntryID operation middleware
func (siw *ServerInterfaceWrapper) GetGetDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", chi.URLParam(r, "table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "entryID" -------------
	var entryID string

	err = runtime.BindStyledParameterWithOptions("simple", "entryID", chi.URLParam(r, "entryID"), &entryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGetDataTableUserIDEntryID(w, r, table, userID, entryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGetFileUserIDEntryID operation middleware
func (siw *ServerInterfaceWrapper) GetGetFileUserIDEntryID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "entryID" -------------
	var entryID string

	err = runtime.BindStyledParameterWithOptions("simple", "entryID", chi.URLParam(r, "entryID"), &entryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGetFileUserIDEntryID(w, r, userID, entryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGetPasswordUsername operation middleware
func (siw *ServerInterfaceWrapper) GetGetPasswordUsername(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGetPasswordUsername(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGetUserIDUsername operation middleware
func (siw *ServerInterfaceWrapper) GetGetUserIDUsername(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGetUserIDUsername(w, r, username)
	}))

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostLogin(w, r)
	}))

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostRegister operation middleware
func (siw *ServerInterfaceWrapper) PostRegister(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRegister(w, r)
	}))

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostSendFileUserID operation middleware
func (siw *ServerInterfaceWrapper) PostSendFileUserID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "fileName" -------------
	var fileName string

	err = runtime.BindStyledParameterWithOptions("simple", "fileName", chi.URLParam(r, "fileName"), &fileName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileName", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSendFileUserID(w, r, userID, fileName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutUpdateDataTableUserIDEntryID operation middleware
func (siw *ServerInterfaceWrapper) PutUpdateDataTableUserIDEntryID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", chi.URLParam(r, "table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	// ------------- Path parameter "userID" -------------
	var userID int

	err = runtime.BindStyledParameterWithOptions("simple", "userID", chi.URLParam(r, "userID"), &userID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userID", Err: err})
		return
	}

	// ------------- Path parameter "entryID" -------------
	var entryID string

	err = runtime.BindStyledParameterWithOptions("simple", "entryID", chi.URLParam(r, "entryID"), &entryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutUpdateDataTableUserIDEntryID(w, r, table, userID, entryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/addData/{table}/{userID}/{entryID}", wrapper.PostAddDataTableUserIDEntryID)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/deleteData/{table}/{userID}/{entryID}", wrapper.DeleteDeleteDataTableUserIDEntryID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getAllData/{table}/{userID}", wrapper.GetGetAllDataTableUserID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getData/{table}/{userID}/{entryID}", wrapper.GetGetDataTableUserIDEntryID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getFile/{userID}/{entryID}", wrapper.GetGetFileUserIDEntryID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getPassword/{username}", wrapper.GetGetPasswordUsername)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getUserID/{username}", wrapper.GetGetUserIDUsername)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.PostLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/register", wrapper.PostRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sendFile/{userID}/{fileName}", wrapper.PostSendFileUserID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/updateData/{table}/{userID}/{entryID}", wrapper.PutUpdateDataTableUserIDEntryID)
	})

	return r
}
